### ISSUE TITLE
Add tool to company (Amazon uses Dafny)

### ISSUE THREAD

**Issue by alvinary** [ligurio/practical-fm#35]
Amazon uses Dafny to verify cryptographic protocols

These are two relevant links :)
https://github.com/aws/aws-encryption-sdk-dafny
https://zetzsche.st/

I didn't find a 'pull request etiquette howto', so I opened an issue!

**Comment by ligurio** [comment]
Could you create pr?

**Comment by alvinary** [comment]
Ok! Hold on  a bit :) I'll create a fork, add the tool, and see if it looks good before creating the pr!
